// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCJvcG0MMa5ZpggPuSZVmgjQWv11bAdXo',
    appId: '1:77665692902:web:a268e33ee8609168b4df27',
    messagingSenderId: '77665692902',
    projectId: 'clinicadental-97531',
    authDomain: 'clinicadental-97531.firebaseapp.com',
    storageBucket: 'clinicadental-97531.firebasestorage.app',
    measurementId: 'G-PCBMX9GZW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTAvVSDIWTvMBcHg5qMd9PkbNRcqnnXI',
    appId: '1:77665692902:android:9c764fd1bd2d1ac3b4df27',
    messagingSenderId: '77665692902',
    projectId: 'clinicadental-97531',
    storageBucket: 'clinicadental-97531.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCJvcG0MMa5ZpggPuSZVmgjQWv11bAdXo',
    appId: '1:77665692902:web:8464b149526ccf56b4df27',
    messagingSenderId: '77665692902',
    projectId: 'clinicadental-97531',
    authDomain: 'clinicadental-97531.firebaseapp.com',
    storageBucket: 'clinicadental-97531.firebasestorage.app',
    measurementId: 'G-LYGF3JPHHJ',
  );
}
